sudo: false
language: node_js

cache:
  directories:
    - node_modules

services:
  - xvfb

branches:
  only:
    - master

notifications:
  email:
    on_failure: change

node_js:
  - '10'

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - npm i -g npm

script:
  - npm run test:ci
  - npm run build
