name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        job:
          - lint
          - test -- --no-watch --no-progress --browsers=ChromeHeadless
          - build

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: install
      run: npm ci

    - name: Run ${{ matrix.job }}
      run: npm run ${{ matrix.job }}
